[target.thumbv7em-none-eabihf]
rustflags = [
    "-C", "link-arg=-Tlink.x",
]

[build]
target = "thumbv7em-none-eabihf"

[alias]
t = "test --target aarch64-apple-darwin --lib"
b = "build"
bd = "build --release"
